sudo: false

language: node_js

services:
  - docker

node_js:
  - 16

install:
  - npm i

script:
  - npm i
  - npm run lint
  - docker run -it --entrypoint=bash -v `pwd`:/root/tmp --rm macacajs/macaca-electron-docker-ubuntu -c "cd /root/tmp && ./test/ci.sh"
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls